FROM dreg.eust0.cyberarmorsoft.com:443/k8s-base-image:latest
RUN echo $(date -u) > /build_date.txt

COPY ./k8s-ca-dashboard-aggregator . 

CMD /k8s-ca-dashboard-aggregator
ENTRYPOINT ["./k8s-ca-dashboard-aggregator"]
