name: build
on:
  pull_request_target:
    types: [closed]
    branches:
    - 'master'
    - 'main'
    paths-ignore:
      - '**.md' ### Ignore running when README.MD changed.
      - '.github/workflows/*' ### Ignore running when files under path: .github/workflows/* changed.

  # push:
  #   tags:
  #     - 'v*'

jobs:
  pr-merged:
    if: ${{ github.event.pull_request.merged == true }} ## Skip if not merged
    uses: kubescape/workflows/.github/workflows/incluster-comp-pr-merged.yaml@main
    with:
      IMAGE_NAME: quay.io/${{ github.repository_owner }}/kollector
      IMAGE_TAG: v0.1.${{ github.run_number }}
      COMPONENT_NAME: kollector
      CGO_ENABLED: 0
      GO111MODULE: ""
      BUILD_PLATFORM: linux/amd64,linux/arm64
      GO_VERSION: "1.23"
      REQUIRED_TESTS: '[
                        "vuln_scan", 
                        "vuln_scan_trigger_scan_on_new_image", 
                        "vuln_scan_trigger_scan_public_registry", 
                        "vuln_scan_trigger_scan_public_registry_excluded", 
                        "vuln_scan_trigger_scan_private_quay_registry", 
                        "vuln_scan_triggering_with_cron_job", 
                        "registry_scanning_triggering_with_cron_job", 
                        "ks_microservice_ns_creation",
                        "ks_microservice_on_demand", 
                        "ks_microservice_mitre_framework_on_demand", 
                        "ks_microservice_nsa_and_mitre_framework_demand", 
                        "ks_microservice_triggering_with_cron_job", 
                        "ks_microservice_update_cronjob_schedule", 
                        "ks_microservice_delete_cronjob", 
                        "ks_microservice_create_2_cronjob_mitre_and_nsa"
                      ]'
      COSIGN: true
      HELM_E2E_TEST: true
    secrets: inherit
